# Licensed to Apache Software Foundation (ASF) under one or more contributor
# license agreements. See the NOTICE file distributed with
# this work for additional information regarding copyright
# ownership. Apache Software Foundation (ASF) licenses this file to you under
# the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

{{- if .Values.standalone.httpSvc }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "banyandb.fullname" . }}-http
  labels:
    app: {{ template "banyandb.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.standalone.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    {{- range $key, $value := .Values.standalone.httpSvc.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  annotations:  
    {{- range $key, $value := .Values.standalone.httpSvc.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  type: {{ .Values.standalone.httpSvc.type }}
  ports:
    - port: {{ .Values.standalone.httpSvc.port }}
      name: http
  selector:
    app: {{ template "banyandb.name" . }}
    component: "{{ .Values.standalone.name }}"
    release: {{ .Release.Name }}
  {{- if .Values.standalone.httpSvc.externalIPs }}
  externalIPs:
    {{- range $v := .Values.standalone.httpSvc.externalIPs }}
    - {{ $v }}
    {{- end }}
  {{- end }}
  {{- if .Values.standalone.httpSvc.loadBalancerIP }}
  loadBalancerIP: {{ .Values.standalone.httpSvc.loadBalancerIP }}
  {{- end }}
  {{- if .Values.standalone.httpSvc.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- range $v := .Values.standalone.httpSvc.loadBalancerSourceRanges }}
    - {{ $v }}
    {{- end }}
  {{- end }}
{{- end}}